version: '3.4'

services:

  nextjs-frontend:
    build:
      dockerfile: frontend.dockerfile
    restart: always
    env_file:
      - .env

networks:
  default:
    external:
      name: backend_app-network