services:
  caddy-service:
    image: caddy:2.7.6-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - fastapi-backend
      - grafana
      - redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network: