import "../styles/globals.css";
import { ReactQueryProvider } from "./ReactQueryProvider";
import AuthContext from "./context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body>
          <AuthContext>{children}</AuthContext>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
