name: Deployment

on:
  workflow_run:
    workflows: ["Unit Testing (Container)", "Cypress Tests"]
    types:
      - completed

jobs:
  deployment-job:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'production'
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} <<-EOF
            cd webapp
            git checkout production
            git pull
            cd frontend
            npm run build 
            pm2 restart all --update-env
            cd ..
            cd backend
            ./rebuild.sh
          EOF
