name: Deployment

on:
  push:
    branches:
      - production

jobs:
  unit-tests:
    uses: ./.github/workflows/unit_test.yml
    secrets: inherit

  e2e-tests:
    uses: ./.github/workflows/e2e_test.yml
    secrets: inherit

  deployment-job:
    needs: [unit-tests, e2e-tests]
    if: ${{ needs.unit-tests.outputs.passed == 'true' && needs.e2e-tests.outputs.passed == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} <<-EOF
            cd webapp
            git checkout production
            git pull
            cd frontend
            npm run build 
            pm2 restart all --update-env
            cd ..
            cd backend
            ./rebuild.sh
          EOF
