name: Unit Testing
on:
  push:
    branches:
      - development
      - production
jobs:
  frontendtest:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./frontend/~.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Lint code
        run: npm run lint
        working-directory: ./frontend
      - name: Run Unit Tests
        run: npm run test
        working-directory: ./frontend
