name: Unit Testing (Container)
on:
  push:
    branches:
      - development
      - production
jobs:
  frontendtest:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: oven-sh/setup-bun@v1
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3

        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: bun list

      - name: Compile node modules
        run: |
          bun install
          bun run build
        working-directory: ./frontend
      - name: Lint code
        run: npm run lint
        working-directory: ./frontend
      - name: Run Unit Tests
        run: npm run test
        working-directory: ./frontend
  backendtest:
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: development
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache-poetry
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install Poetry dependencies
        run: poetry install
        working-directory: ./backend
      - name: Run Unit Tests and setup secrets env
        run: poetry run pytest
        env:
          CONTENT_EXPIRE: ${{ secrets.CONTENT_EXPIRE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
          JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRE_MINUTES }}
          JWT_REFRESH_TOKEN_EXPIRE_MINUTES: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRE_MINUTES }}
          JWT_AUTH_TOKEN: ${{ secrets.JWT_AUTH_TOKEN }}
          POSTGRES_HOST: "127.0.0.1"
          POSTGRES_PORT: "5432"
          POSTGRES_USERNAME: "admin"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DATABASE: "development"
          REDIS_BROKER: "redis://127.0.0.1:6379/0"
          REDIS_BACKEND: "redis://127.0.0.1:6379/0"
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: "6379"
          APP_ENV: "github"
          TNSR_DOMAIN: "http://127.0.0.1:3000"
        working-directory: ./backend
